README.md, src/main/java/com/amihaiemil/docker/Containers.java, src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/Exec.java, src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/Networks.java, src/main/java/com/amihaiemil/docker/Volumes.java, src/main/java/com/amihaiemil/docker/placeholder.md
Fixes #1 
Added the first interfaces of the api.
=> First interfaces

src/main/java/com/amihaiemil/docker/RtDocker.java
Added RtDocker and puzzle for implementing a Request (jcabi-http) that can talk via unix sockets.
=> RtDocker + puzzle for unix Request

pom.xml, src/main/java/com/amihaiemil/docker/BaseRequest.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/UnixSocket.java
Fixes #7 
Added temporary copy of jcabi-http's BaseRequest, until a new version (with it public) is released.
=> UnixSocket scaffolding

src/main/java/com/amihaiemil/docker/BaseRequest.java, src/main/java/com/amihaiemil/docker/UnixSocket.java
The HTTP request is created and sent over the socket. Next thing: implement the Response and write some tests for this class.
=> UnixSocket.send started implementation + puzzles

.travis.yml, src/main/java/com/amihaiemil/docker/SocketResponse.java, src/main/java/com/amihaiemil/docker/UnixSocket.java, src/test/java/com/amihaiemil/docker/SocketResponseTestCase.java, src/test/java/com/amihaiemil/docker/placeholder.md
Implementation for #14 
Also enabled test coverage.
=> SocketResponse

checkstyle.xml, src/main/java/com/amihaiemil/docker/LocalDocker.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
=> LocalDocker implemented

README.md, pom.xml, src/main/java/com/amihaiemil/docker/LocalDocker.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/UnixSocket.java, src/test/java/com/amihaiemil/docker/LocalDockerITCase.java
Implemented Docker.ping(), added the first integration test + build profile for integration tests.
=> Docker.ping() + LocalDockerITCase

src/test/java/com/amihaiemil/docker/RtContainersTestCase.java
This PR:
* Solves #53 
* Adds tests for `RtContainers.create(String, String)`, `RtContainers.create(String, JsonObject)`, and `RtContainers.create(JsonObject)`
@amihaiemil let me know if these tests are enough
=> (#53) Added tests for RtContainers

src/main/java/com/amihaiemil/docker/RtContainer.java, src/main/java/com/amihaiemil/docker/RtContainers.java, src/main/java/com/amihaiemil/docker/UnexpectedResponseException.java, src/test/java/com/amihaiemil/docker/RtContainerTestCase.java, src/test/java/com/amihaiemil/docker/UnexpectedResponseExceptionTestCase.java
=> added UnexpectedResponseException

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/RtSwarm.java, src/main/java/com/amihaiemil/docker/Swarm.java, src/test/java/com/amihaiemil/docker/RtSwarmTestCase.java
This PR:
* solves #3 
* Uses the [Docker Swarm API Docs](https://docs.docker.com/engine/api/v1.35/#tag/Swarm) as reference
* Adds new `Swarm` with `inspect()` method
* Leaves puzzle to finish adding and impementing the rest of the Swarm methods
* Leaves puzzle to finish implementing the rest of the Docker methods (except for Swarm)
* Leaves puzzle for a refactoring of "inspect" operations in general
=> (#3) Added new Swarm interface with inspect() method

src/main/java/com/amihaiemil/docker/Container.java, src/main/java/com/amihaiemil/docker/RtContainer.java, src/test/java/com/amihaiemil/docker/RtContainerTestCase.java
This PR:
* solves #57 
* implements `Container.stop`
* Uses the [Docker API Docs](https://docs.docker.com/engine/api/v1.35/#tag/Container) as reference
* Leaves a  puzzle for the rest
=> (#57) Implemented Container.stop()

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/Image.java, src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/RtImage.java, src/main/java/com/amihaiemil/docker/RtImages.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java, src/test/java/com/amihaiemil/docker/mock/Response.java
This PR:
* solves #71 by implementing `Images.iterate()`
* Uses the [Images API Docs](https://docs.docker.com/engine/api/v1.35/#operation/ImageList) as reference
* Leaves puzzle for the rest of the `Docker` interface
* Leaves puzzle for the rest of the `Images` interface
* Fixes puzzle format in Response.java.
=> (#71) Implemented Images.iterate() : Iterable<Image>

src/main/java/com/amihaiemil/docker/RtSwarm.java, src/main/java/com/amihaiemil/docker/Swarm.java, src/test/java/com/amihaiemil/docker/RtSwarmTestCase.java
PR for #77 
Implemented Swarm.leave and added unit tests. Left puzzle for continuing.
=> #77 Swarm.leave + unit tests

src/main/java/com/amihaiemil/docker/RemoteDocker.java, src/main/java/com/amihaiemil/docker/SslHttpClient.java, src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java
PR for #67 
Added Path to certificates and puzzle for continuing
=> #67 path to certs

src/main/java/com/amihaiemil/docker/Container.java, src/main/java/com/amihaiemil/docker/RtContainer.java, src/test/java/com/amihaiemil/docker/RtContainerTestCase.java
=> Container.rename + unit tests

src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/RtImages.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
This PR:
* solves #98 
* Implements `Images.prune()`
* Leaves puzzle for the rest
=> (#98) Implemented Images.prune()

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/LocalDocker.java, src/main/java/com/amihaiemil/docker/RemoteDocker.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java, src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java
Pr for #68 
* Added more unit tests for ``RemoteDocker``
* cleaned a little, throw Unsupporded exception from unimplemented methods
* Add and test method ``Docker.version()``
=> unit tests + version()

src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/RtImages.java
=> Images.iterator() + puzzle

src/main/java/com/amihaiemil/docker/Containers.java, src/main/java/com/amihaiemil/docker/ReadJsonObject.java, src/main/java/com/amihaiemil/docker/RtContainers.java, src/main/java/com/amihaiemil/docker/RtImages.java, src/test/java/com/amihaiemil/docker/RtContainerITCase.java, src/test/java/com/amihaiemil/docker/RtContainersITCase.java, src/test/java/com/amihaiemil/docker/RtContainersTestCase.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
Added iteration for Containers.
Still need to write an integration test.
=> Containers iterator

src/main/java/com/amihaiemil/docker/Container.java, src/main/java/com/amihaiemil/docker/Logs.java, src/main/java/com/amihaiemil/docker/RtContainer.java, src/main/java/com/amihaiemil/docker/RtLogs.java, src/test/java/com/amihaiemil/docker/RtContainerTestCase.java, src/test/java/com/amihaiemil/docker/RtLogsTestCase.java
PR for #128 
Added and unit tested ``Container.logs()`` and left puzzle to continue
=> Container.logs() + unit tests

src/main/java/com/amihaiemil/docker/ReadJsonArray.java, src/main/java/com/amihaiemil/docker/ReadLogsStream.java, src/main/java/com/amihaiemil/docker/RtLogs.java, src/test/java/com/amihaiemil/docker/RtLogsTestCase.java
=> RtLogs.follow() + unit test

src/main/java/com/amihaiemil/docker/ReadStream.java, src/main/java/com/amihaiemil/docker/ReadString.java, src/main/java/com/amihaiemil/docker/RtLogs.java, src/main/java/com/amihaiemil/docker/RtSwarm.java, src/test/java/com/amihaiemil/docker/RtLogsTestCase.java
=> RtLogs.fetch() and toString() + unit tests

src/test/java/com/amihaiemil/docker/mock/Response.java, src/test/java/com/amihaiemil/docker/mock/ResponseTestCase.java
=> mock Response.toString() + unit test

src/main/java/com/amihaiemil/docker/Container.java, src/main/java/com/amihaiemil/docker/Containers.java, src/main/java/com/amihaiemil/docker/Image.java, src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/RtContainer.java, src/main/java/com/amihaiemil/docker/RtContainers.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/RtImage.java, src/main/java/com/amihaiemil/docker/RtImages.java, src/main/java/com/amihaiemil/docker/RtSwarm.java, src/main/java/com/amihaiemil/docker/Swarm.java, src/test/java/com/amihaiemil/docker/RtContainerTestCase.java, src/test/java/com/amihaiemil/docker/RtContainersTestCase.java, src/test/java/com/amihaiemil/docker/RtImageTestCase.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java, src/test/java/com/amihaiemil/docker/RtSwarmTestCase.java
PR for #143 
Added ``.docker()`` convenience method, so the client can always access the Docker engine that the Container, Image etc comes from.
=> #143 added and tested method docker()

src/main/java/com/amihaiemil/docker/Images.java, src/main/java/com/amihaiemil/docker/RtImages.java, src/test/java/com/amihaiemil/docker/ListedImagesTestCase.java
PR for #152 
Added Images.save(), unit test for ListedImages.iterate() and puzzles
=> Images.save + ListedImages unit test

pom.xml
=> Better json-p dependencies

.gitignore, src/main/java/com/amihaiemil/docker/IdentityToken.java, src/test/java/com/amihaiemil/docker/IdentityTokenTestCase.java
This PR is for #171:
* Implemented `IdentityToken`
* Left puzzle to finish tying it all together - the `Auth`s, the `AuthHttpClient`, and the user
* git-ignored a Netbeans-specific folder just so I don't have to keep manually sidestepping it :)
=> (#171) IdentityToken

src/main/java/com/amihaiemil/docker/DiskSpaceInfo.java, src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/DockerSystem.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/RtDockerSystem.java, src/main/java/com/amihaiemil/docker/SystemDiskSpaceInfo.java, src/test/java/com/amihaiemil/docker/RtDockerSystemITCase.java, src/test/java/com/amihaiemil/docker/RtDockerSystemTestCase.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
Implementation of the call to System API, method df. It shows disk space usage for images, containers and volumes, and total disk usage in bytes.
=> #194 - Implementing system/df API call

src/main/java/com/amihaiemil/docker/ListedImages.java
PR for #186. Since this is old task, removing puzzle and trying to close it using PR.
=> Fixing #186

src/main/java/com/amihaiemil/docker/RtVolumes.java, src/main/java/com/amihaiemil/docker/Volumes.java, src/test/java/com/amihaiemil/docker/RtVolumesTestCase.java
For #206:
- added prune method to Volumes 
- added unit tests for RtVolumes
=> For #206. Adding prune method to Volumes

src/main/java/com/amihaiemil/docker/ListedVolumes.java, src/test/java/com/amihaiemil/docker/ListedVolumesTestCase.java
For #207:
- Added filtering injection into `ListedVolumes`
- Created test to assure that `ListedVolumes` is filtering correctly the volumes
=> For #207: Added tests to volume filtering

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/Plugin.java, src/main/java/com/amihaiemil/docker/Plugins.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
For #175:
- adding Plugins API initial interface
=> For #175: Adding Plugins API interface.

src/main/java/com/amihaiemil/docker/Auth.java, src/main/java/com/amihaiemil/docker/RemoteDocker.java, src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java
https://github.com/amihaiemil/docker-java-api/issues/193
=> RemoteDocker authentication

src/main/java/com/amihaiemil/docker/JsonResource.java
https://github.com/amihaiemil/docker-java-api/issues/202
=> JsonResource improvements

.travis.yml, src/main/java/com/amihaiemil/docker/RtContainer.java, src/test/java/com/amihaiemil/docker/RtContainerITCase.java
For #180:
- adding more ITs for RtContainer to cover: stop, restart, kill methods.
- for Travis CI: pull ubuntu Docker image to enable RtContainer ITs
=> For #180: Adding more ITs for RtContainer.

src/main/java/com/amihaiemil/docker/ListedNetworks.java, src/main/java/com/amihaiemil/docker/Network.java, src/main/java/com/amihaiemil/docker/RtNetwork.java, src/main/java/com/amihaiemil/docker/RtNetworks.java, src/test/java/com/amihaiemil/docker/ListedNetworksTestCase.java, src/test/java/com/amihaiemil/docker/RtNetworkTestCase.java, src/test/java/com/amihaiemil/docker/RtNetworksTest.java
For #173:
- Implementing create and prune for Networks interface
- Skeleton for implementing all methods of Network interface
=> For #173 Implementing Network Create and Prune

src/main/java/com/amihaiemil/docker/Auth.java, src/main/java/com/amihaiemil/docker/AuthHttpClient.java, src/main/java/com/amihaiemil/docker/Credentials.java, src/main/java/com/amihaiemil/docker/IdentityToken.java, src/main/java/com/amihaiemil/docker/RegistryConfigAuth.java, src/test/java/com/amihaiemil/docker/AuthHttpClientTestCase.java, src/test/java/com/amihaiemil/docker/IdentityTokenTestCase.java, src/test/java/com/amihaiemil/docker/RegistryConfigAuthTestCase.java
For #208:
- refactoring AuthHttpClient to support one more method of authentication (with X-Registry-Config header), which is used when building images
=> For #208: Issue 208 auth http client

src/main/java/com/amihaiemil/docker/Networks.java, src/main/java/com/amihaiemil/docker/RtNetworks.java, src/test/java/com/amihaiemil/docker/RtNetworksTest.java
For #224 
- Added method create with parameters 
- Added test to check if network was created with parameters
=> For #224: add create method with additional parameters

src/main/java/com/amihaiemil/docker/ListedNetworks.java, src/test/java/com/amihaiemil/docker/ListedNetworksTestCase.java
For #226: Added test method for ListedNetworks.iterate
=> For #226: Implement ListedNetwork filters

src/test/java/com/amihaiemil/docker/RtNetworkTestCase.java
=> For #227: removed puzzle

src/main/java/com/amihaiemil/docker/ListedImages.java, src/main/java/com/amihaiemil/docker/ListedVolumes.java, src/main/java/com/amihaiemil/docker/UncheckedUriBuilder.java, src/test/java/com/amihaiemil/docker/ListedVolumesTestCase.java
For https://github.com/amihaiemil/docker-java-api/issues/214:
- `ListedVolumes` filter implemented;
- `UncheckedUriBuilder` improvements;
=> Filter implemented for ListedVolumes.

src/main/java/com/amihaiemil/docker/FilteredUriBuilder.java, src/main/java/com/amihaiemil/docker/UncheckedUriBuilder.java, src/test/java/com/amihaiemil/docker/FilteredUriBuilderTest.java
For #240: 
- added FilteredUriBuilder wrapper
- added FilteredUriBuilderTest class with tests
- updated puzzle
=> For #240: added UriBuilder wrapper and tests

src/main/java/com/amihaiemil/docker/ListedPlugins.java, src/main/java/com/amihaiemil/docker/Plugins.java, src/main/java/com/amihaiemil/docker/RtPlugins.java, src/test/java/com/amihaiemil/docker/RtNetworksTestCase.java, src/test/java/com/amihaiemil/docker/RtPluginsTestCase.java
For #221:
- implemented create() and pullAndInstall() methods
=> For #221: Implementing create and pullAndInstall methods for Plugins API

src/main/java/com/amihaiemil/docker/Networks.java, src/main/java/com/amihaiemil/docker/RtNetworks.java, src/test/java/com/amihaiemil/docker/RtNetworksTestCase.java
For #235:
- finished implementing create with additional parameters
=> For #235: Implementing create with additional parameters

src/main/java/com/amihaiemil/docker/RegistryConfigAuth.java
For #230: Extend RegistryConfigAuth to support multiple registries
=> For #230: Extend RegistryConfigAuth to support multiple registries

src/main/java/com/amihaiemil/docker/ListedNetworks.java, src/test/java/com/amihaiemil/docker/ListedNetworksTestCase.java
For #237:
- Implemented listing Networks using filters
=> For #237 Implemented listing Networks with filters

src/main/java/com/amihaiemil/docker/Network.java
=> For #236: Puzzle removal.

src/main/java/com/amihaiemil/docker/RtVolumes.java, src/main/java/com/amihaiemil/docker/Volumes.java, src/test/java/com/amihaiemil/docker/RtVolumesTestCase.java
For #213: 
- creating volumes with parameters like driver, driver options and labels
- also returning proper Volume object on create.
=> For #213 Creating volumes with parameters

src/main/java/com/amihaiemil/docker/ListedPlugins.java, src/main/java/com/amihaiemil/docker/Plugin.java, src/main/java/com/amihaiemil/docker/Plugins.java, src/main/java/com/amihaiemil/docker/RtPlugin.java, src/main/java/com/amihaiemil/docker/RtPlugins.java, src/test/java/com/amihaiemil/docker/ListedPluginsTestCase.java, src/test/java/com/amihaiemil/docker/RtPluginTestCase.java
For #251: 
- listing Plugins with filters
- created all other support interfaces/classes
- created a new puzzle to finish Plugin implementation
=> For #251: Listing plugins with filter

src/main/java/com/amihaiemil/docker/Plugin.java, src/test/java/com/amihaiemil/docker/RtPluginTestCase.java
For #266: 
- Added tests for two conditions of `RtPlugin#enable` and `RtPlugin#disable`;
- Left todos for the rest of  implementation
=> For #266: RtPlugin#enable and #disable tests.

src/main/java/com/amihaiemil/docker/PluginPrivilege.java, src/main/java/com/amihaiemil/docker/Plugins.java, src/main/java/com/amihaiemil/docker/RtPlugins.java, src/test/java/com/amihaiemil/docker/RtPluginsTestCase.java
For #250:
- Implementing retrieving plugin privileges for specified name
=> For #250: Plugin privileges

src/main/java/com/amihaiemil/docker/ListedPlugins.java
For #251:
- forgot to remove puzzle to be able to close ticket
=> For #251: Removing puzzle

src/main/java/com/amihaiemil/docker/Logs.java, src/main/java/com/amihaiemil/docker/RtLogs.java, src/test/java/com/amihaiemil/docker/RtLogsTestCase.java
For #258:
- Implemented Logs.all(), Logs.stdout() and Logs.stderr().
=> For #258: Implemented Logs all(), stodout() and stderr()

src/main/java/com/amihaiemil/docker/RtPlugin.java, src/test/java/com/amihaiemil/docker/RtPluginTestCase.java
For #269:
- Implementing enable and disable methods
- Fixing tests
=> For #269: Implementing Plugin enable() and disable() methods

src/main/java/com/amihaiemil/docker/RtImages.java, src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
For #276:
- Implementing `importImage` method.
=> For #276: Implementing Images importImage() method

src/test/java/com/amihaiemil/docker/RtPluginTestCase.java, src/test/java/com/amihaiemil/docker/RtPluginsTestCase.java, src/test/java/com/amihaiemil/docker/mock/StringPayloadOf.java
For #283:
- Creating new class `StringPayloadOf` to help minimize test code duplication
=> For #283: Creating StringPayloadOf class for tests

src/main/java/com/amihaiemil/docker/Plugin.java, src/main/java/com/amihaiemil/docker/RtPlugin.java, src/test/java/com/amihaiemil/docker/RtPluginTestCase.java
For #284:
- Implementing Plugin's `configure` method.
=> For #284: Implementing Plugin configure() method

pom.xml
For #287:
- Adding Automatic-Module-Name to Manifest when profile is release
=> For #287: Adding Automatic-Module-Name to Manifest of release jar

src/main/java/com/amihaiemil/docker/DockerSystem.java, src/main/java/com/amihaiemil/docker/RtDockerSystem.java
PR for #296 
Added a first verison of events monitoring.
=> #296 events() first sketch

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/DockerSystem.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/RtDockerSystem.java, src/test/java/com/amihaiemil/docker/LocalDockerITCase.java, src/test/java/com/amihaiemil/docker/RtDockerSystemITCase.java
=> #296 fix events() path

README.md
PR for #303 
Updated itcases setup.
=> Updated itcases setup

src/test/java/com/amihaiemil/docker/RtImagesITCase.java
Add integration tests for filters.
=> Add integration tests for filters

.travis.yml, pom.xml
=> Added testCoverage Maven Profile

src/main/java/com/amihaiemil/docker/RtDocker.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java, src/test/java/com/amihaiemil/docker/TcpDockerTestCase.java, src/test/java/com/amihaiemil/docker/UnixDockerTestCase.java
PR for #167 
Implemented RtDocker.networks()
=> Added implementation of network method for class RtDocker and test for it

src/main/java/com/amihaiemil/docker/Docker.java, src/main/java/com/amihaiemil/docker/Execs.java, src/main/java/com/amihaiemil/docker/RtDocker.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java, src/test/java/com/amihaiemil/docker/UnixDockerTestCase.java
PR for #168 
* ``Execs`` (plural) represents the ``Exec API`` entry point and is an ``Iterable<Exec>``
* ``Exec`` is a single batch of commands created by a ``Container``.
=> #168 Execs entrypoint iterable of Exec

src/main/java/com/amihaiemil/docker/RtDocker.java, src/main/java/com/amihaiemil/docker/RtExecs.java, src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java, src/test/java/com/amihaiemil/docker/UnixDockerTestCase.java
PR for #168
Next up: implement ``RtExec``.
=> #168 implemented Docker.execs()

src/main/java/com/amihaiemil/docker/ReadLogString.java, src/main/java/com/amihaiemil/docker/RtLogs.java, src/test/java/com/amihaiemil/docker/RtLogsITCase.java, src/test/java/com/amihaiemil/docker/RtLogsTestCase.java
=> 302: Add custom reader for docker logs

src/main/java/com/amihaiemil/docker/ListedNetworks.java, src/main/java/com/amihaiemil/docker/Networks.java, src/test/java/com/amihaiemil/docker/ListedNetworksTestCase.java
=> 167: Added filtering for Networks

src/test/java/com/amihaiemil/docker/RtEventsTestCase.java
=> #299 unit tests for RtEvents
