amihaiemil/docker-java-api

src/main/java/com/amihaiemil/docker/SocketResponse.java
src/test/java/com/amihaiemil/docker/SocketResponseTestCase.java

Implemented and tested headers()

---

src/main/java/com/amihaiemil/docker/SocketResponse.java
src/test/java/com/amihaiemil/docker/SocketResponseTestCase.java

Read plain or chunked body + tests

---

src/main/java/com/amihaiemil/docker/LocalDocker.java
src/main/java/com/amihaiemil/docker/UnixHttpClient.java
src/test/java/com/amihaiemil/docker/UnixHttpClientTestCase.java

fix for #29 
Added UnixHttpClient which will encapsulate an HttpClient, make it work with a UnixSocket.

UnixHttpClient, unit tests and puzzle

---

src/main/java/com/amihaiemil/docker/LocalDocker.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/UnixHttpClient.java
src/test/java/com/amihaiemil/docker/LocalDockerITCase.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
src/test/java/com/amihaiemil/docker/UnixHttpClientTestCase.java

#32 UnixHttpClient fully implemented and tested

---

src/main/java/com/amihaiemil/docker/LocalDocker.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java

#36 /_ping implemented + puzzle

---

src/main/java/com/amihaiemil/docker/Docker.java
src/main/java/com/amihaiemil/docker/LocalDocker.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
src/test/java/com/amihaiemil/docker/UnixHttpClientTestCase.java
src/test/java/com/amihaiemil/docker/mock/AssertRequest.java

as per #38:
This PR:
* Added primary ctor to `LocalDocker`
* Added `AssertRequest`, a mock HttpClient useful for testing requests
* Fixed typo in interface `Docker`
* Reduces the scope of the puzzle of "create a unix socket server" to just the testing of `UnixHttpClient`
* Leaves a puzzle to advance the design of `AssertRequest`

#38: Preparing LocalDocker for testing

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/Containers.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/main/java/com/amihaiemil/docker/RtContainers.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

Pr for #28 
Started implementation of RtContainers and RtContainer.

RtContainers, RtContainer started + puzzles

---

src/test/java/com/amihaiemil/docker/mock/AssertRequest.java
src/test/java/com/amihaiemil/docker/mock/AssertRequestTestCase.java
src/test/java/com/amihaiemil/docker/mock/Condition.java

This PR:
* Solves #42
* Adds new `Condition` class to support our tests
* `AssertRequest` now accepts `Condition` instead of `Predicate<HttpRequest>`
* Adds a few tests for `AssertRequest`

#42: Added 'Condition' and wrote a few tests for AssertRequest

---

src/main/java/com/amihaiemil/docker/UnixHttpClient.java
src/test/java/com/amihaiemil/docker/UnixHttpClientITCase.java

This PR:
* Solves #44 
* `UnixHttpClient`: swapped BasicHttpClientConnectionManager for PoolingHttpClientConnectionManager
* Leaves puzzle due to impediment on #41 
* Leaves puzzle to make the pool size configurable

(#44) Changed ConnectionManager for UnixHttpClient

---

src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java
src/test/java/com/amihaiemil/docker/mock/PayloadOf.java
src/test/java/com/amihaiemil/docker/mock/Response.java

This PR:
* solves #47
* Uses as reference the [Docker ContainerCreate API Docs](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate)
* Adds some tests for `RtContainers`
* Adds new test support classes `Response` and `PayloadOf`
* Fixes typo in 'ContainerCreate' API endpoint in `RtContainers`
* Leaves puzzle due to impediment on #45 
* Leaves puzzle to finish implementing the rest of test cases on `RtContainers`

(#47) Wrote some unit tests for RtContainers

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

PR for #46 implemented and unit tested Container.inspect and Container.start. Left puzzle for continuing implementation.

Container inspect and start + unit tests

---

.travis.yml

This PR:
* solves #55 
* Uses as reference the [Travis Docs](https://docs.travis-ci.com/user/docker/)
* enables docker + integration tests in the Travis build
Note: the coverage provided by the integration tests will be included in the coveralls report.

(#55) Enabled docker + integration tests in Travis build

---

src/main/java/com/amihaiemil/docker/LocalDocker.java
src/main/java/com/amihaiemil/docker/UnixHttpClient.java
src/main/java/com/amihaiemil/docker/UnixSocketFactory.java

This PR:
* solves #52 
* Externalizes the anonymous unix ConnectionSocketFactory into `UnixSocketFactory`
* Makes `LocalDocker(HttpClient, String)` public for users to provide their own HttpClient
* Adds some javadocs

(#52) Configuration of Unix connection pooling

---

src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

This PR:
* Solves #54 
* Removes `@Ignore` on tests for `RtContainers` previously blocked by #45

(#54) Unignored tests for RtContainers that depended on #45

---

src/main/java/com/amihaiemil/docker/DefaultHttpClient.java
src/main/java/com/amihaiemil/docker/RemoteDocker.java
src/main/java/com/amihaiemil/docker/SslHttpClient.java
src/test/java/com/amihaiemil/docker/DefaultHttpClientTestCase.java
src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java
src/test/java/com/amihaiemil/docker/SslHttpClientTestCase.java

This PR:
* solves #23
* Adds `RemoteDocker`
* Adds `SslHttpClient` implementing connection pooling
* Adds some tests for both
* Leaves puzzle to finish testing `RemoteDocker`
Note:
The implementation of `SslHttpClient` is very minimal. I think we can just implement its operations as their need arises. It's also the reason why I added very few tests for it. It's the major reason why coverage decreases with this PR.

(#23) Implemented RemoteDocker

---

src/main/java/com/amihaiemil/docker/Inspection.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/InspectionTestCase.java

This PR:
* solves #72 
* Adds new reusable `Inspection` class for *.inspect() methods
* Refactored `RtSwarm.inspect` and `RtContainer.inspect` accordingly
* Adds missing license header in `RtContainer` and `PayloadOf`
If we need to implement another `JsonObject` later on then we really should make a base "envelope" for all....

(#72) New 'Inspection' class

---

src/test/java/com/amihaiemil/docker/mock/Response.java
src/test/java/com/amihaiemil/docker/mock/UnixServer.java

This PR:
* Advances work for #79 
* Leaves puzzle for finishing touches and testing
References:
* [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html)
* My own sample taken with wireshark showing structure of a simple response from a random web page:
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 12 Apr 2018 13:43:53 GMT
Content-Length: 951
[some random json]
```

(#79) Draft for sending responses back to clients from the mock UnixServer

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

This PR:
* solves #76 
* Uses this [documentation](https://docs.docker.com/engine/api/v1.35/#operation/ContainerRestart) as reference
* leaves puzzle for the rest
Note: I'm not sure if it's worth overloading `restart()` with a `timeout` parameter (see the linked docs)

(#76) Implemented Container.restart()

---

src/main/java/com/amihaiemil/docker/Image.java
src/main/java/com/amihaiemil/docker/RtImage.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImageTestCase.java

PR for #86 
Implemented and unit tested the 2 methods. What is interesting is that ``Image.history`` returns an instance of ``Images``, since that's what they are: previous layers (versions) which constituted ``this Image`` over time.
We will have to make a better design in ``RtImages.iterate`` since now we don't always have to append ``/json`` when iterationg.

#86 Image.inspect, Image.history + unit tests

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

PR for #88 
Implemented and unit tested Container#kill. Left todo for the rest.
**Note:** We are starting to have quite some code duplication inside ``restart()``, ``stop()`` and ``kill()``. Any suggestion on how we could get rid of it elegantly?

#88 Container.kill + unit tests

---

src/main/java/com/amihaiemil/docker/RtImages.java
src/main/java/com/amihaiemil/docker/UncheckedUriBuilder.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
src/test/java/com/amihaiemil/docker/mock/Response.java

This PR:
* Solves #83
* Uses the [ImageCreate](https://docs.docker.com/engine/api/v1.35/#operation/ImageCreate) docs as reference
* Adds helper class `UncheckedUriBuilder`
* Adds new ctor to `Response` for responses w/o payload
* Leaves puzzle to implement reusable [Authentication](https://docs.docker.com/engine/api/v1.35/#section/Authentication)
* Leaves puzzle for the rest of the `Images` operations

(#83) Implemented Images.create()

---

src/main/java/com/amihaiemil/docker/Image.java
src/main/java/com/amihaiemil/docker/RtImage.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImageTestCase.java

This PR:
* Solves #96 
* Leaves puzzle for the rest

(#96) Implemented Image.delete()

---

src/main/java/com/amihaiemil/docker/MatchStatus.java
src/test/java/com/amihaiemil/docker/MatchStatusTestCase.java
src/test/java/com/amihaiemil/docker/mock/AssertRequest.java

PR for #93 
Left puzzle for using this handler to reduce code duplication.

MatchStatus + unit tests

---

.travis.yml
src/main/java/com/amihaiemil/docker/Inspection.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerITCase.java

PR for #58 
Started writing Integration tests

#58 IT case for Container#rename

---

src/main/java/com/amihaiemil/docker/Image.java
src/main/java/com/amihaiemil/docker/RtImage.java
src/test/java/com/amihaiemil/docker/RtImageTestCase.java

This PR:
* solves #103 
* uses the [ImageTag Docs](https://docs.docker.com/engine/api/v1.35/#operation/ImageTag) as reference
* Implements `Image.tag()`

(#103) Implemented Image.tag()

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/Inspection.java
src/main/java/com/amihaiemil/docker/JsonResource.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

PR for #114 
Introduced ``JsonResource`` which should be extended by all the Json entities of the API (Container, Image etc). This is for:
* polymorphism (we will be able to have common iteration logic, for instance)
* avoiding n+1 query problem.
Before this mechanism, the biggest issue was that the returned JsonObject (from the creation time) was not retained and thus, the client would have to call ``inspect()`` everytime they wanted some info about it, even data that can't be changed over time.

JsonObject polymorphism and avoid n+1 query

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerITCase.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

Container.remove + tests

---

src/main/java/com/amihaiemil/docker/Image.java
src/main/java/com/amihaiemil/docker/Images.java
src/main/java/com/amihaiemil/docker/JsonResource.java
src/main/java/com/amihaiemil/docker/ReadJsonArray.java
src/main/java/com/amihaiemil/docker/ResourcesIterator.java
src/main/java/com/amihaiemil/docker/RtImage.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImageTestCase.java
src/test/java/com/amihaiemil/docker/RtImagesITCase.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java

RtImages now uses ``ResourceIterator`` to iterate over all the images, with the default filters. Wrote unit tests and integration tests.
Had to introduce ``ReadJsonArray`` response handler, which wraps ``MatchStatus`` because apparently once we pass a response handler to ``HttpClient.execute(...)``, it automatically closes the response and you cannot read from it after the handlers have executed.

ResourceIterator implemented for RtImages

---

src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

(#109) RtContainers.create(): URL encode the query parameters

---

src/main/java/com/amihaiemil/docker/RemoteDocker.java
src/main/java/com/amihaiemil/docker/SslHttpClient.java
src/test/java/com/amihaiemil/docker/SslHttpClientTestCase.java

This PR:
* Parametrizes key/trust stores for `SslHttpClient` as per #100 
* Differs a bit from the problem description in the way the user configures the keys: the user should just provide a path to their keystore where their keys are, while the server's public key should have been previously imported into their truststore, and the path to this truststore should be provided as well
* Leaves puzzle for adding tests for `SslHttpClient`
* Leaves puzzle for adding an insecure http client because someone may also wish to disable security on their docker API

(#100) Initial SSLContext implementation for SslHttpClient

---

src/main/java/com/amihaiemil/docker/JsonResource.java
src/main/java/com/amihaiemil/docker/MatchStatus.java
src/main/java/com/amihaiemil/docker/PayloadOf.java
src/main/java/com/amihaiemil/docker/UnexpectedResponseException.java
src/test/java/com/amihaiemil/docker/InspectionTestCase.java
src/test/java/com/amihaiemil/docker/MatchStatusTestCase.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
src/test/java/com/amihaiemil/docker/RtSwarmTestCase.java
src/test/java/com/amihaiemil/docker/UnexpectedResponseExceptionTestCase.java
src/test/java/com/amihaiemil/docker/mock/Response.java

This PR:
* solves #108 
* Adds `UnexpectedResponseException.payload()`
* Promotes `PayloadOf` from test packages to production packages as a package-private class
* Does small fix to a bunch of test cases that started to fail as soon as we started parsing the HttpResponse non-json payloads
* Leaves puzzle for adding tests to `PayloadOf`

(#108) Add the body to the UnexpectedResponseException

---

src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

For #133.
My solution was to merge both JSON objects and pass that to `RtContainer`. The merge is done by building a new `JsonObject` from scratch because `JsonObject`s are immutable.

(#133) Injecting JsonObject parameter and JsonObject response to RtContainer

---

src/main/java/com/amihaiemil/docker/Image.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtImage.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImageTestCase.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java

For #127:
* Implemented `Image.run()`: basically a shortcut for `Container.create(image); Container.start();`
* The `Docker` instance is now passed down through `RtDocker` -> `RtImages` -> `RtImage` to enable `RtImage` to create containers.

(#127) Image.run()

---

src/main/java/com/amihaiemil/docker/RemoteDocker.java

PR for #147 
RemoteDocker is now public and usable. The client has to configure the HttpClient according to their needs.

RemoteDocker with HttpClient

---

src/main/java/com/amihaiemil/docker/FilteredImages.java
src/main/java/com/amihaiemil/docker/Images.java
src/main/java/com/amihaiemil/docker/ListedImages.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java

PR for #144 
RtImages is abstract since we will have at least 2 implementations: ``ListedImages`` and ``SearchedImages``, which will be iterated differently (use a different HTTP endpont).
Left a few puzzles for continuing implementation in different areas.

Added ListedImages and made RtImages abstract

---

src/main/java/com/amihaiemil/docker/Network.java
src/main/java/com/amihaiemil/docker/Networks.java
src/main/java/com/amihaiemil/docker/RtNetwork.java
src/main/java/com/amihaiemil/docker/RtNetworks.java
src/test/java/com/amihaiemil/docker/RtNetworksTest.java

This PR is for #85:
* Initial implementations of `Networks` and `Network`
* Left puzzles to continue work

(#85) RtNetworks, RtNetwork

---

src/main/java/com/amihaiemil/docker/ListedImages.java
src/test/java/com/amihaiemil/docker/ListedImagesTestCase.java

This PR is for #154:
* Adds filtering capability for `ListedImages` according to [the docs](https://docs.docker.com/engine/api/v1.35/#operation/ImageList).
This PR took me way longer than it looks. The documentation referenced above is not entirely clear, and searches for some examples yield filters not included in the documentation(!) ([1](https://stackoverflow.com/questions/39976683/docker-api-can-t-apply-json-filters), [2](https://stackoverflow.com/a/49974198/1623885)).
I have not tested this solution against a live docker instance, and I'm not quite satisfied both with the efficiency of the unit test I wrote, nor with the elegance of both the implementation and test. `¯\_(ツ)_/¯` Maybe we can add a puzzle for that. Maybe we can also wait for #153 and make sure this actually works when …

(#154) Filters for ListedImages

---

src/main/java/com/amihaiemil/docker/Images.java
src/main/java/com/amihaiemil/docker/ListedImages.java
src/test/java/com/amihaiemil/docker/ListedImagesTestCase.java
src/test/java/com/amihaiemil/docker/RtImagesITCase.java

This PR is for #153:
* Sketch of `Images.filter()` in `ListedImages`
* Left puzzle for implementing integration tests for `RtImages.filter()`
I'm also not so sure what the merge strategy should be for these filters. This PR will simply substitute any previously specified filter's values, but I'm not sure if you wanted to actually *merge* the values of the filters.

(#153) Images.filter()

---

src/main/java/com/amihaiemil/docker/Containers.java
src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

PR for #161, added option to fetch all containers, not only the running ones.

Containers.all() + unit test

---

src/main/java/com/amihaiemil/docker/Docker.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java

Docker.httpClient() + unit tests

---

src/main/java/com/amihaiemil/docker/ListedVolumes.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtVolumes.java
src/main/java/com/amihaiemil/docker/Volume.java
src/main/java/com/amihaiemil/docker/Volumes.java
src/test/java/com/amihaiemil/docker/LocalDockerTestCase.java
src/test/java/com/amihaiemil/docker/RemoteDockerTestCase.java

This PR is for #169 :
- Added ListVolumes, RtVolumes and Volume.
- Setup the basic volumes and add a new puzzle.

(#169) Added new volume classes

---

src/main/java/com/amihaiemil/docker/HttpClientEnvelope.java
src/main/java/com/amihaiemil/docker/PlainHttpClient.java
src/main/java/com/amihaiemil/docker/RemoteDocker.java
src/main/java/com/amihaiemil/docker/UnixHttpClient.java
src/test/java/com/amihaiemil/docker/SslHttpClientTestCase.java
src/test/java/com/amihaiemil/docker/UnixHttpClientTestCase.java

This PR is for #176:
* Added `HttpClientEnvelope`
* Refactored existing http clients to extend `HttpClientEnvelope`
* Added `PlainHttpClient`
* Added ctor for `RemoteDocker` that defaults to the `PlainHttpClient`

(#176) HttpClientEnvelope + PlainHttpClient

---

src/main/java/com/amihaiemil/docker/ListedVolumes.java
src/main/java/com/amihaiemil/docker/RtVolume.java
src/main/java/com/amihaiemil/docker/RtVolumes.java
src/main/java/com/amihaiemil/docker/Volume.java
src/main/java/com/amihaiemil/docker/Volumes.java
src/test/java/com/amihaiemil/docker/ListedVolumesTestCase.java
src/test/java/com/amihaiemil/docker/RtVolumeTestCase.java

PR for #192. Extending iterable of Volumes plus providing a couple of new puzzles

Implementing iterable Volumes - fixing issue #192

---

src/main/java/com/amihaiemil/docker/AuthHttpClient.java

Close #172. Creating new puzzle to create new Auth client

---

.travis.yml

https://github.com/amihaiemil/docker-java-api/issues/197

dind container setup for integration tests

---

src/main/java/com/amihaiemil/docker/RtVolume.java
src/main/java/com/amihaiemil/docker/RtVolumes.java
src/main/java/com/amihaiemil/docker/Volume.java
src/main/java/com/amihaiemil/docker/Volumes.java
src/test/java/com/amihaiemil/docker/ListedVolumesTestCase.java
src/test/java/com/amihaiemil/docker/RtVolumeTestCase.java
src/test/java/com/amihaiemil/docker/RtVolumesTestCase.java

For #205:
- implementing delete and basic create method for Volumes API
- creating testcases
- creating new pdd to extend create method with more options (specify driver, driver options and labels)

For #205: Adding Volume delete and create methods

---

src/main/java/com/amihaiemil/docker/Network.java
src/test/java/com/amihaiemil/docker/RtNetworkTestCase.java

For #225: Added test methods for Network.connect and Network.disconnect

For #225: Implement the rest of Network methods

---

src/main/java/com/amihaiemil/docker/RtNetwork.java
src/test/java/com/amihaiemil/docker/RtNetworkTestCase.java

For #236:
- Added the code remaining to `RtNetwork` related too all other operations
- Fixed the tests, that were wrong; the actual tests check if we are making the correct request to docker API

For #236: Added the rest of RtNetwork methods and fixed tests

---

src/main/java/com/amihaiemil/docker/Images.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java

For #170: 
- Added test to Images.import
- Left todo for continue to implement Images methods

For #170: Added tests to Images.import

---

src/main/java/com/amihaiemil/docker/FilteredUriBuilder.java
src/main/java/com/amihaiemil/docker/ListedImages.java
src/main/java/com/amihaiemil/docker/ListedVolumes.java
src/main/java/com/amihaiemil/docker/UncheckedUriBuilder.java
src/test/java/com/amihaiemil/docker/FilteredUriBuilderTest.java

For #243:
- implementing adding Json filters to FilteredUriBuilder

For #243: Adding filters to FilteredUriBuilder

---

src/main/java/com/amihaiemil/docker/ListedNetworks.java
src/main/java/com/amihaiemil/docker/RtLogs.java
src/test/java/com/amihaiemil/docker/RtLogsITCase.java
src/test/java/com/amihaiemil/docker/RtLogsTestCase.java

PR for #256. Apparently, it is mandatory to specify either ``stdout`` or ``stderr`` when reading the logs. Left some puzzles.

logs stdout, stderr and integration tests

---

src/main/java/com/amihaiemil/docker/Images.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/java/com/amihaiemil/docker/RtImagesTestCase.java
src/test/resources/images.tar.txt

For #254:
- Renaming importImages to importFromTar (because of the Docker documentation:
https://docs.docker.com/engine/api/v1.35/#operation/ImageLoad
- Implementing Images.importFromTar method

For #254: Implementing Images.importFromTar method

---

src/main/java/com/amihaiemil/docker/ArrayPayloadOf.java
src/main/java/com/amihaiemil/docker/Plugin.java
src/main/java/com/amihaiemil/docker/RtPlugin.java
src/test/java/com/amihaiemil/docker/RtPluginTestCase.java
src/test/java/com/amihaiemil/docker/RtPluginsTestCase.java
src/test/java/com/amihaiemil/docker/mock/ArrayPayloadOf.java

For #268:
- Implementing `upgrade()` and `push()` methods
- Added new class `ArrayPayloadOf` to extract Json request as `Iterator<JsonObject>`
- Added new puzzles: to make tests for `ArrayPayloadOf` and to finish Plugin's `configure()` method

For #268: Implementing Plugin upgrade() and push() methods

---

src/main/java/com/amihaiemil/docker/Images.java

For #276:
- Removing puzzle for implementing `importImage` method.

For #276: Removing puzzle for importImage

---

src/main/java/com/amihaiemil/docker/Images.java
src/main/java/com/amihaiemil/docker/RtImages.java
src/test/resources/placeholder.md

PR for #277 
The method is now returning ``this``, since ``Images`` will always iterate over the existing images (this means also the newly imported ones will be iterated).

Images.importFromTar() :: Images

---

src/main/java/com/amihaiemil/docker/ListedVolumes.java
src/test/java/com/amihaiemil/docker/ListedVolumesTestCase.java
src/test/java/com/amihaiemil/docker/LocalDockerITCase.java

For #252:
- Implementing `Volumes.iterate()` differently since Volume API returns JsonObject which holds an array of Volumes objects.

#252 Fixing LocalDockerITCase for iterating volumes.

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerITCase.java

PR for #179 
Adding pause and unpause features.

Adding pause and unpause features.

---

src/main/java/com/amihaiemil/docker/Containers.java
src/main/java/com/amihaiemil/docker/ListedContainers.java
src/main/java/com/amihaiemil/docker/RtContainers.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/ListedContainersTestCase.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

This PR extends the container listing API documented in [https://docs.docker.com/engine/api/v1.35/#operation/ContainerList](https://docs.docker.com/engine/api/v1.35/#operation/ContainerList).
All parameters except `limit` are now supported, especially `size` and `filters`.

Implemented more API complete container listing

---

pom.xml

For #312: Added test coverage limits to project:
- added jacoco plugin to `pom.xml`
- configure jacoco to run on `jacoco` profile
- added coverage limits to the project. As the project now fails when the code coverage is not meet I had to leave some of them below the suggested coverage (0.85)

For #312: Added test coverage limits to project.

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/main/java/com/amihaiemil/docker/UnixDocker.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

Adds a `container.waitOn()` function to wait for a container to complete. I did not add an integration test because the integration tests do not seem to work on my dev machine (https://github.com/amihaiemil/docker-java-api/issues/303).

Add call to container/{id}/wait

---

src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtExec.java
src/main/java/com/amihaiemil/docker/RtExecs.java
src/test/java/com/amihaiemil/docker/RtExecsTestCase.java

PR for #168 
Implemented and used ``RtExec``, as well as the ``inspect()`` method.

#168 RtExec, inspect() method and unit test

---

src/main/java/com/amihaiemil/docker/Docker.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/test/java/com/amihaiemil/docker/LocalDockerITCase.java
src/test/java/com/amihaiemil/docker/UnixDockerITCase.java

PR for #299 
* Docker.events() returns an infinite Stream of JsonObject events (added JavaDocs about the call to ``Stream.limit()`` being mandatory).

Stream :: docker.events()

---

src/main/java/com/amihaiemil/docker/Docker.java
src/main/java/com/amihaiemil/docker/Events.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtEvents.java
src/test/java/com/amihaiemil/docker/LocalDockerITCase.java
src/test/java/com/amihaiemil/docker/UnixDockerITCase.java

PR for #299 
We cannot expose a Stream directly, we need to let the user specify the query parameters as well. Thus, we need the ``Events`` abstraction.
Still needs unit tests.

#299 Events/RtEvents implemented; needs tests

---

src/main/java/com/amihaiemil/docker/Docker.java
src/main/java/com/amihaiemil/docker/Info.java
src/main/java/com/amihaiemil/docker/RtDocker.java
src/main/java/com/amihaiemil/docker/RtInfo.java
src/main/java/com/amihaiemil/docker/RtVersion.java
src/main/java/com/amihaiemil/docker/Version.java
src/test/java/com/amihaiemil/docker/UnixDockerITCase.java
src/test/java/com/amihaiemil/docker/UnixDockerTestCase.java

Fixes #344 
* implemented ``Info :: docker.info()``
* added unit tests and integration test
* also added missing integration test for ``docker.version()``

Implemented docker.info()

---

src/main/java/com/amihaiemil/docker/Container.java
src/main/java/com/amihaiemil/docker/RtContainer.java
src/test/java/com/amihaiemil/docker/RtContainerITCase.java
src/test/java/com/amihaiemil/docker/RtContainerTestCase.java

PR for #168  
Added method to create an ``Exec``.

add implementation of method exec for Container

---

src/main/java/com/amihaiemil/docker/Containers.java
src/main/java/com/amihaiemil/docker/RtContainers.java
src/test/java/com/amihaiemil/docker/RtContainersTestCase.java

Get method
